### ISSUE TITLE
访问的时候务如何在url中加上secret参数？？

### ISSUE THREAD

**Issue by xujianjun229** [1002victor/zlm_webassist#2]
请问访问的时候务如何在url中加上secret参数，有示例url吗？http://default.zlmediakit.com/ 直接用这个域名可以不？

**Comment by linj121** [comment]
在URL后面加上`?secret=<secret值>`，比如[https://default.zlmediakit.com/webassist/?secret=123](https://default.zlmediakit.com/webassist?secret=123)，注意webassist后有个`/`，确保资源加载路径是正确的。

> 请问访问的时候务如何在url中加上secret参数，有示例url吗？[http://default.zlmediakit.com](http://default.zlmediakit.com/) 直接用这个域名可以不？
