### ISSUE TITLE
添加拉流代理后重启服务代理就没了

### ISSUE THREAD

**Issue by Leslie-Hung** [1002victor/zlm_webassist#5]
如题

**Comment by 1002victor** [comment]
该项目是一个纯前端API接口调用，无数据库，不做任何保存哈，仅作为zlm的运行监控测试使用^-^，另外zlm自身也不带数据库，重启后添加的代理也就没了。有保存需求可以考虑使用wvp，或者自己撸代码接管添加代理的操作业务逻辑

**Comment by Leslie-Hung** [comment]
> 该项目是一个纯前端API接口调用，无数据库，不做任何保存哈，仅作为zlm的运行监控测试使用^-^，另外zlm自身也不带数据库，重启后添加的代理也就没了。有保存需求可以考虑使用wvp，或者自己撸代码接管添加代理的操作业务逻辑
好的

**Comment by Leslie-Hung** [comment]
好的
